---
language: python
python:
- '2.6'
- '2.7'
before_install:
- sudo apt-get update
- sudo apt-get install libevent-dev
install:
    - pip install -r requirements.txt --use-mirrors
    - pip install coverage
before_script: python setup.py pep8
script: nosetests --with-cover --cover-html --cover-package=decanter
notifications:
  irc: irc.freenode.net#Gengo
after_success: ./scripts/update-gh-pages.sh

env:
  global:
    secure: ! 'Q31R6Btx/xygBKDwYrMhGSV9vnbZ5hwSsS0+txtAZIRmsygA9SApQU4z81xq

      AfQsfjQq20sTCrea1VCeI5vnn/ZvehGIC2pqt/9cFu7vcTLIK+c8Wyyr+o57

      5mk6hUvnVLk22j+KWWwhf4XaiE/I/Fov40S+d1InEtIkD6ReJ38='

